# Generated by Django 5.0.14 on 2025-05-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dogparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogparent',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Кличка родителя'),
        ),
    ]
